language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.1
  - 2.11.8

env:
  - TEST_SUITE=scoobie
  - TEST_SUITE=postgres40
  - TEST_SUITE=postgres41

script:
  - bash scripts/build.sh $TEST_SUITE

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database world;' -U postgres
  - psql -q -c '\i world.sql' -d world -U postgres
  - psql -d world -c "create extension postgis" -U postgres
  - psql -d world -c "create type myenum as enum ('foo', 'bar')" -U postgres

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name “*.lock” -type f -delete
  - find $HOME/.ivy2/cache -name “ivydata-*.properties” -type f -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e7f5152049eff61e3376
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

